### ISSUE TITLE
短时间有做英文主页的打算么

### ISSUE THREAD

**Issue by specter119** [Fndroid/clash-win-docs#2]
想把 clash-for-windows 加到 scoop-extra 里，那边说有英文主页才给放。
如果短时间木有计划，就不加他们的源了，见 https://github.com/lukesampson/scoop-extras/pull/2131 。
我都看到有人维护自己的 scoop 源了。

**Comment by Fndroid** [comment]
暂时没有计划

**Comment by specter119** [comment]
好的，谢谢。
