### ISSUE TITLE
建议将文档链接放在clash-for-window README中

### ISSUE THREAD

**Issue by Jackiexiao** [Fndroid/clash-win-docs#8]
之前在网上搜索clash的教程一直没找到全的，辗转几次之后才发现这里，在clash-for-window repo中点进wiki界面也没有找到文档。建议可以将文档放在显眼的位置

**Comment by Fndroid** [comment]
软件里feedback里不是有么？

**Comment by Jackiexiao** [comment]
get，之前没留意
